import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#012d1d',
        'on-primary': '#ffffff',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        secondary: '#2c694e',
        'on-secondary': '#ffffff',
        'secondary-container': '#aeeecb',
        'on-secondary-container': '#316e52',
        tertiary: '#332300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4e3800',
        'on-tertiary-container': '#d19e14',
        'tertiary-fixed': '#ffdfa0',
        'tertiary-fixed-dim': '#f6be39',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5c4300',
        surface: '#fcf8ff',
        'surface-dim': '#dad7f3',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#efecff',
        'surface-container-high': '#e8e5ff',
        'surface-container-highest': '#e2e0fc',
        'surface-tint': '#3f6653',
        'on-surface': '#1a1a2e',
        'on-surface-variant': '#414844',
        'inverse-surface': '#2f2e43',
        'inverse-on-surface': '#f2efff',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
        background: '#fcf8ff',
        'on-background': '#1a1a2e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        'secondary-fixed': '#b1f0ce',
        'secondary-fixed-dim': '#95d4b3',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#0e5138',
        'inverse-primary': '#a5d0b9',
        'surface-variant': '#e2e0fc',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'display-lg': ['var(--font-playfair)', 'serif'],
        'display-lg-mobile': ['var(--font-playfair)', 'serif'],
        'headline-lg': ['var(--font-cormorant)', 'serif'],
        'headline-md': ['var(--font-cormorant)', 'serif'],
        'body-lg': ['var(--font-dm-sans)', 'sans-serif'],
        'body-md': ['var(--font-dm-sans)', 'sans-serif'],
        'label-price': ['var(--font-sora)', 'sans-serif'],
        'quote-italic': ['var(--font-eb-garamond)', 'serif'],
      },
    },
  },
  plugins: [],
}

export default config
